apiVersion: v1
kind: Service
metadata:
  name: swift
  namespace: kube-system
  labels:
    app: swift
spec:
  
  ports:
  - name: pt
    port: 9855
    targetPort: pt
  - name: tls
    port: 50055
    targetPort: tls
  - name: ops
    port: 56790
    targetPort: ops
  selector:
    app: swift
  type: LoadBalancer  
